version: '3'

services:
  # 从库
  mysql-slave:
    image: mysql:8.0
    container_name: mysql-slave
    ports:
      - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: everforcc
      MYSQL_PASSWORD: everforcc
      MYSQL_DATABASE: db_test_sync
    volumes:
      - ./slave/my.cnf:/etc/mysql/my.cnf
      - ./slave/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mysql-network

  # 主库一
  mysql-master1:
    image: mysql:8.0
    container_name: mysql-master1
    ports:
      - "3311:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: everforcc
      MYSQL_PASSWORD: everforcc
      MYSQL_DATABASE: db_test_sync
    volumes:
      - ./master1/my.cnf:/etc/mysql/my.cnf
      - ./master1/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mysql-network

  # 主库二
  mysql-master2:
    image: mysql:8.0
    container_name: mysql-master2
    ports:
      - "3312:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: everforcc
      MYSQL_PASSWORD: everforcc
      MYSQL_DATABASE: db_test_sync
    volumes:
      - ./master2/my.cnf:/etc/mysql/my.cnf
      - ./master2/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mysql-network

  # 主库三
  mysql-master3:
    image: mysql:8.0
    container_name: mysql-master3
    ports:
      - "3313:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: everforcc
      MYSQL_PASSWORD: everforcc
      MYSQL_DATABASE: db_test_sync
    volumes:
      - ./master3/my.cnf:/etc/mysql/my.cnf
      - ./master3/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mysql-network

networks:
  mysql-network:
    driver: bridge 